# Generated by Django 3.0.6 on 2021-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.TextField(null=True),
        ),
    ]
